/**
 * Virtual module generator for navigation
 *
 * Generates the virtual:ssg-navigation module that exports
 * the navigation structure for all collections.
 */

import type { SSGConfig, NavSection, NavItem, CollectionConfig } from '../types';
import type { SSGRoute } from '../types';
import { generateAllCollections, detectCollection as detectCollectionImpl, CollectionNavigation } from './navigation';

/**
 * Virtual module ID for SSG navigation
 */
export const VIRTUAL_NAVIGATION_ID = 'virtual:ssg-navigation';
export const RESOLVED_VIRTUAL_NAVIGATION_ID = '\0' + VIRTUAL_NAVIGATION_ID;

/**
 * Navigation module result type
 */
export interface NavigationModule {
    /** Navigation keyed by collection name */
    navigation: Record<string, CollectionNavigation>;
    /** Collections configuration for path detection */
    collections: Record<string, CollectionConfig>;
}

/**
 * Generate the virtual navigation module code
 *
 * @param routes - Scanned SSG routes with metadata
 * @param config - SSG configuration
 * @param isDev - Whether running in development mode
 */
export function generateNavigationModule(
    routes: SSGRoute[],
    config: SSGConfig,
    isDev: boolean
): string {
    const navigation = generateAllCollections(routes, config, isDev);
    const collections = config.collections || {};

    // Serialize navigation and collections to JSON
    const navJson = JSON.stringify(navigation, null, 2);
    const collectionsJson = JSON.stringify(collections, null, 2);

    return `
/**
 * Auto-generated navigation module
 * 
 * @generated by @sigx/ssg
 */

/**
 * Navigation for all collections, keyed by collection name
 */
export const navigation = ${navJson};

/**
 * Collections configuration
 */
const collections = ${collectionsJson};

/**
 * Get navigation for a specific collection
 * @param name - Collection name (e.g., 'docs', 'examples')
 * @returns The collection's navigation or undefined if not found
 */
export function getCollectionNav(name) {
    return navigation[name];
}

/**
 * Detect which collection a route path belongs to
 * @param path - Current route path
 * @returns The collection name if found, undefined otherwise
 */
export function detectCollection(path) {
    // Sort by normalized (trailing-slash-trimmed) path length descending so the
    // most specific collection wins, matching the boundary check below
    // (signalxjs/ssg#143).
    const normLength = (p) => p.replace(/\\/+$/, '').length;
    const sorted = Object.entries(collections).sort(
        ([, a], [, b]) => normLength(b.path) - normLength(a.path)
    );

    for (const [name, config] of sorted) {
        // Match on a path-segment boundary so '/modules/updates-ui/x' is not
        // claimed by the '/modules/updates' collection (signalxjs/ssg#143).
        const prefix = config.path.replace(/\\/+$/, '');
        if (path === prefix || path.startsWith(prefix + '/')) {
            return name;
        }
    }

    return undefined;
}

/**
 * Get sidebar for a specific collection
 * @param name - Collection name
 * @returns The sidebar array or empty array if not found
 */
export function getSidebar(name) {
    return navigation[name]?.sidebar || [];
}

export default { navigation, collections, getCollectionNav, detectCollection, getSidebar };
`;
}

/**
 * Create a loader for the navigation module
 */
export async function loadNavigationModule(
    routes: SSGRoute[],
    config: SSGConfig,
    isDev: boolean
): Promise<{ navigation: Record<string, CollectionNavigation>; code: string }> {
    const navigation = generateAllCollections(routes, config, isDev);
    const code = generateNavigationModule(routes, config, isDev);
    return { navigation, code };
}
