/**
 * Sidebar Component
 *
 * Documentation sidebar with nested navigation.
 * Uses auto-generated navigation from virtual:ssg-navigation when no items prop provided.
 * Supports multi-collection navigation with auto-detection from current route.
 */

import { component } from 'sigx';
import { RouterLink, useRoute } from '@sigx/router';

// Import from virtual module - will be generated by SSG plugin
// Falls back to empty navigation if virtual module not available
let generatedNavigation: Record<string, { sidebar: NavSection[] }> = {};
let detectCollection: (path: string) => string | undefined = () => undefined;

try {
    // @ts-ignore - Virtual module may not exist in all contexts
    const navModule = await import('virtual:ssg-navigation');
    generatedNavigation = navModule.navigation || {};
    detectCollection = navModule.detectCollection || (() => undefined);
} catch {
    // Virtual module not available - use props or defaults
}

export interface SidebarItem {
    title: string;
    href?: string;
    items?: SidebarItem[];
    order?: number;
}

export interface NavSection {
    title: string;
    items: SidebarItem[];
    order?: number;
}

export interface SidebarProps {
    /**
     * Custom sidebar items. If not provided, uses auto-generated navigation
     * from virtual:ssg-navigation.
     */
    items?: SidebarItem[];
    
    /**
     * Sections with category headers. Takes precedence over flat items.
     */
    sections?: NavSection[];

    /**
     * Collection name to display navigation for.
     * If not provided, auto-detects from current route path.
     */
    collection?: string;
}

export default component<SidebarProps>(({ props }) => {
    const route = useRoute();
    
    /**
     * Check if a nav item or any of its children is active
     */
    const isItemActive = (item: SidebarItem): boolean => {
        if (item.href && route.path === item.href) {
            return true;
        }
        if (item.items) {
            return item.items.some(isItemActive);
        }
        return false;
    };

    // Determine what to render:
    // 1. Props sections (explicit sections with headers)
    // 2. Props items (flat items without headers)  
    // 3. Auto-generated navigation from collection
    const getSections = (): NavSection[] => {
        if (props.sections) {
            return props.sections;
        }
        if (props.items) {
            // Wrap flat items in a single section
            return [{ title: '', items: props.items }];
        }
        
        // Auto-detect or use explicit collection
        const collectionName = props.collection || detectCollection(route.path);
        
        if (!collectionName) {
            // No collection detected - show nothing
            if ((import.meta as any).env?.DEV) {
                console.warn(`[Sidebar] No collection found for path: ${route.path}`);
            }
            return [];
        }

        const collectionNav = generatedNavigation[collectionName];
        if (!collectionNav) {
            if ((import.meta as any).env?.DEV) {
                console.warn(`[Sidebar] Collection "${collectionName}" not found in navigation`);
            }
            return [];
        }

        return collectionNav.sidebar || [];
    };

    const renderItem = (item: SidebarItem, depth = 0) => {
        const isActive = item.href ? route.path === item.href : false;
        const hasActiveChild = item.items ? item.items.some(isItemActive) : false;

        if (item.items && item.items.length > 0) {
            return (
                <li>
                    <details open={depth === 0 || hasActiveChild}>
                        <summary class="font-semibold">{item.title}</summary>
                        <ul>
                            {item.items.map((child) => renderItem(child, depth + 1))}
                        </ul>
                    </details>
                </li>
            );
        }

        return (
            <li>
                <RouterLink 
                    to={item.href || '#'} 
                    class={`hover:bg-base-300 ${isActive ? 'active bg-primary/20 text-primary font-medium' : ''}`}
                >
                    {item.title}
                </RouterLink>
            </li>
        );
    };

    return () => {
        const sections = getSections();
        
        return (
            <nav class="sidebar">
                <ul class="menu menu-sm bg-base-200 rounded-box w-full">
                    {sections.map((section) => (
                        <>
                            {section.title && (
                                <li class="menu-title">
                                    <span>{section.title}</span>
                                </li>
                            )}
                            {section.items.map((item) => renderItem(item))}
                        </>
                    ))}
                </ul>
            </nav>
        );
    };
});
