/**
 * Virtual Entry Point Generation
 * 
 * Generates auto-configured client and server entry points for zero-config mode.
 * Users can override by providing their own entry files.
 */

import fs from 'node:fs';
import path from 'node:path';
import type { SSGConfig } from '../types';

/**
 * Virtual module IDs
 * Note: We use a special path format that Vite can resolve from HTML
 */
export const VIRTUAL_CLIENT_ID = 'virtual:ssg-client';
export const RESOLVED_VIRTUAL_CLIENT_ID = '\0' + VIRTUAL_CLIENT_ID + '.tsx';

// Special entry path that can be used in HTML and resolved by the plugin
export const SSG_CLIENT_ENTRY_PATH = '/@ssg/client.tsx';

export const VIRTUAL_SERVER_ID = 'virtual:ssg-server';
export const RESOLVED_VIRTUAL_SERVER_ID = '\0' + VIRTUAL_SERVER_ID + '.tsx';

export const VIRTUAL_HTML_ID = 'virtual:ssg-html';
export const RESOLVED_VIRTUAL_HTML_ID = '\0' + VIRTUAL_HTML_ID;

/**
 * Detection result for custom entry points
 */
export interface EntryDetectionResult {
    /** Whether to use virtual client entry */
    useVirtualClient: boolean;
    /** Whether to use virtual server entry */
    useVirtualServer: boolean;
    /** Whether to use virtual HTML template */
    useVirtualHtml: boolean;
    /** Path to custom client entry if found */
    customClientPath?: string;
    /** Path to custom server entry if found */
    customServerPath?: string;
    /** Path to custom HTML template if found */
    customHtmlPath?: string;
    /** Path to global CSS if found */
    globalCssPath?: string;
}

/**
 * Detect if user has custom entry points
 */
export function detectCustomEntries(root: string, config: SSGConfig): EntryDetectionResult {
    // Custom client entry paths (if found, user has custom setup)
    const clientPaths = [
        'src/main.tsx',
        'src/main.ts',
        'src/entry-client.tsx',
        'src/entry-client.ts',
        'src/entry.tsx',
        'src/entry.ts',
    ];

    const serverPaths = [
        'src/entry-server.tsx',
        'src/entry-server.ts',
    ];

    const htmlPaths = [
        'index.html',
    ];

    // Global CSS to auto-import (checked in order of preference)
    const cssPaths = [
        'src/styles/global.css',
        'src/styles/main.css',
        'src/styles/index.css',
        'src/style.css',
        'src/global.css',
        'src/index.css',
    ];

    let customClientPath: string | undefined;
    let customServerPath: string | undefined;
    let customHtmlPath: string | undefined;
    let globalCssPath: string | undefined;

    // Check for custom client entry
    for (const p of clientPaths) {
        const fullPath = path.join(root, p);
        if (fs.existsSync(fullPath)) {
            customClientPath = fullPath;
            break;
        }
    }

    // Check for custom server entry
    for (const p of serverPaths) {
        const fullPath = path.join(root, p);
        if (fs.existsSync(fullPath)) {
            customServerPath = fullPath;
            break;
        }
    }

    // Check for custom HTML template
    for (const p of htmlPaths) {
        const fullPath = path.join(root, p);
        if (fs.existsSync(fullPath)) {
            customHtmlPath = fullPath;
            break;
        }
    }

    // Check for global CSS
    for (const p of cssPaths) {
        const fullPath = path.join(root, p);
        if (fs.existsSync(fullPath)) {
            globalCssPath = '/' + p.replace(/\\/g, '/');
            break;
        }
    }

    return {
        useVirtualClient: !customClientPath,
        useVirtualServer: !customServerPath,
        useVirtualHtml: !customHtmlPath,
        customClientPath,
        customServerPath,
        customHtmlPath,
        globalCssPath,
    };
}

/**
 * Generate virtual client entry code
 */
export function generateClientEntry(config: SSGConfig, detection: EntryDetectionResult): string {
    const cssImport = detection.globalCssPath
        ? `import '${detection.globalCssPath}';\n`
        : '';

    // Additional client imports from config
    const additionalImports = (config.clientImports ?? [])
        .map(imp => `import '${imp}';`)
        .join('\n');
    const additionalImportsBlock = additionalImports ? `\n${additionalImports}\n` : '';

    const prefetchDelay = typeof config.prefetch === 'object'
        ? config.prefetch.delay ?? 100
        : 100;

    const prefetchEnabled = config.prefetch !== false;

    return `/**
 * Auto-generated client entry point
 * This file is generated by @sigx/ssg when no custom entry is detected.
 * To customize, create src/main.tsx or src/entry-client.tsx
 */
${cssImport}${additionalImportsBlock}
import { defineApp, component } from 'sigx';
import { createRouter, createWebHistory } from '@sigx/router';
import { ssrClientPlugin, installPackageManagerSwitcher${prefetchEnabled ? ', setupPrefetch' : ''} } from '@sigx/ssg/client';
import routes from 'virtual:ssg-routes';
import { setupLayouts, LayoutRouter, setPageProps } from 'virtual:generated-layouts';

// Register the getStaticPaths props the build embedded for this page, so
// hydration renders with the same props the server used (#73).
const embeddedProps = window.__SSG_PROPS__;
if (embeddedProps && embeddedProps.path) {
    setPageProps(embeddedProps.path, embeddedProps.props);
}

// Apply layouts to routes (annotates routes with layout info)
const layoutRoutes = setupLayouts(routes);

// Create router with browser history
const router = createRouter({
    history: createWebHistory({ base: '${config.base || '/'}' }),
    routes: layoutRoutes,
    scrollBehavior(to, from, savedPosition) {
        if (savedPosition) return savedPosition;
        if (to.hash) return { el: to.hash };
        return { top: 0 };
    },
});

// Root app component - uses LayoutRouter which preserves layouts across navigation
const App = component(() => {
    return () => <LayoutRouter />;
});

// Hydrate the server-rendered HTML
defineApp(<App />)
    .use(router)
    .use(ssrClientPlugin)
    .hydrate('#app');

// Enable the npm/pnpm/yarn/bun switcher on install code blocks. Runs after
// hydration so it never races the framework; on pages with no install fences it
// just registers its (cheap) page-wide listeners and does no visible work.
installPackageManagerSwitcher();

${prefetchEnabled ? `// Enable link prefetching for faster navigation
setupPrefetch({ delay: ${prefetchDelay} });` : ''}
`;
}

/**
 * Generate virtual server entry code
 */
export function generateServerEntry(config: SSGConfig): string {
    return `/**
 * Auto-generated server entry point
 * This file is generated by @sigx/ssg when no custom entry is detected.
 * To customize, create src/entry-server.tsx
 */
import { renderToString } from '@sigx/server-renderer/server';
import { defineApp } from 'sigx';
import { createRouter, createMemoryHistory } from '@sigx/router';
import routes from 'virtual:ssg-routes';
import { setupLayouts, LayoutRouter, setPageProps } from 'virtual:generated-layouts';

// Pre-process routes with layouts once at module load time (not per-render)
const routesWithLayouts = setupLayouts(routes);

/**
 * Render the app to HTML string for a given URL
 */
export async function render(url, context) {
    // Register this path's getStaticPaths props so the LayoutRouter passes
    // them to the page component (#73). Keyed by path — concurrent renders
    // sharing this module don't interfere.
    setPageProps(url || '/', context?.props);

    // Create router with memory history for SSR
    // Note: We must create a new router per render because history is URL-specific
    const router = createRouter({
        routes: routesWithLayouts,
        history: createMemoryHistory({
            base: '${config.base || '/'}',
            initialLocation: url || '/',
        }),
    });

    // Create app with router - router's install() sets up DI via app.defineProvide()
    const app = defineApp(<LayoutRouter />).use(router);

    const html = await renderToString(app);
    return html;
}

/**
 * Resolve a dynamic route's getStaticPaths from the bundled page modules.
 * The build calls this instead of import()ing raw .tsx/.mdx sources, which
 * Node cannot load (#46). Returns null when the route has no
 * getStaticPaths export.
 */
export async function getStaticPathsForRoute(routePath) {
    const route = routes.find((r) => r.path === routePath);
    if (!route || typeof route.getStaticPaths !== 'function') {
        return null;
    }
    return route.getStaticPaths();
}
`;
}

/**
 * Generate virtual HTML template (dev server).
 *
 * Per-page-overridable head content (title, description, canonical, OG,
 * Twitter) is emitted by generateHeadTags() in build.ts and injected at
 * the `<!--head-tags-->` marker. In dev mode the marker is not replaced,
 * so a fallback `<title>` from site config keeps the browser tab readable
 * while developing; production builds replace the marker.
 */
export function generateHtmlTemplate(config: SSGConfig): string {
    const site = config.site || {};
    const lang = site.lang || 'en';
    const title = site.title || 'SignalX App';
    const favicon = site.favicon || '/favicon.ico';
    const themeColor = site.themeColor || '#000000';
    const fonts = site.fonts || [];

    // Build font preconnect and stylesheet links
    let fontLinks = '';
    if (fonts.length > 0) {
        fontLinks = `
    <link rel="preconnect" href="https://fonts.googleapis.com" />
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
    <link href="https://fonts.googleapis.com/css2?family=${fonts.join('&family=')}&display=swap" rel="stylesheet" />`;
    }

    return `<!DOCTYPE html>
<html lang="${lang}">
<head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta name="theme-color" content="${themeColor}" />
    <link rel="icon" type="image/x-icon" href="${favicon}" />${fontLinks}
    <title>${title}</title>
    <!--head-tags-->
</head>
<body>
    <div id="app"><!--app-html--></div>
    <script type="module" src="/@ssg/client.tsx"></script>
</body>
</html>
`;
}

/**
 * Generate HTML template for production build.
 *
 * Per-page-overridable head content (title, description, canonical, OG,
 * Twitter) is emitted by generateHeadTags() in build.ts and injected at
 * the `<!--head-tags-->` marker. Keeping copies in this template caused
 * duplicate `<title>` tags in built output and stale OG metadata; the
 * template now only carries truly static head content.
 */
export function generateProductionHtmlTemplate(config: SSGConfig, clientEntryPath: string): string {
    // path.join produces backslashes on Windows — never valid in a URL (#54).
    const entrySrc = clientEntryPath.replace(/\\/g, '/');
    const site = config.site || {};
    const lang = site.lang || 'en';
    const favicon = site.favicon || '/favicon.ico';
    const themeColor = site.themeColor || '#000000';
    const fonts = site.fonts || [];

    // Build font preconnect and stylesheet links
    let fontLinks = '';
    if (fonts.length > 0) {
        fontLinks = `
    <link rel="preconnect" href="https://fonts.googleapis.com" />
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
    <link href="https://fonts.googleapis.com/css2?family=${fonts.join('&family=')}&display=swap" rel="stylesheet" />`;
    }

    return `<!DOCTYPE html>
<html lang="${lang}">
<head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta name="theme-color" content="${themeColor}" />
    <link rel="icon" type="image/x-icon" href="${favicon}" />${fontLinks}
    <!--head-tags-->
</head>
<body>
    <div id="app"><!--app-html--></div>
    <script type="module" src="${entrySrc}"></script>
</body>
</html>
`;
}
