/**
 * Virtual Entry Point Generation
 * 
 * Generates auto-configured client and server entry points for zero-config mode.
 * Users can override by providing their own entry files.
 */

import fs from 'node:fs';
import path from 'node:path';
import type { SSGConfig } from '../types';

/**
 * Virtual module IDs
 * Note: We use a special path format that Vite can resolve from HTML
 */
export const VIRTUAL_CLIENT_ID = 'virtual:ssg-client';
export const RESOLVED_VIRTUAL_CLIENT_ID = '\0' + VIRTUAL_CLIENT_ID + '.tsx';

// Special entry path that can be used in HTML and resolved by the plugin
export const SSG_CLIENT_ENTRY_PATH = '/@ssg/client.tsx';

export const VIRTUAL_SERVER_ID = 'virtual:ssg-server';
export const RESOLVED_VIRTUAL_SERVER_ID = '\0' + VIRTUAL_SERVER_ID + '.tsx';

export const VIRTUAL_HTML_ID = 'virtual:ssg-html';
export const RESOLVED_VIRTUAL_HTML_ID = '\0' + VIRTUAL_HTML_ID;

/**
 * Detection result for custom entry points
 */
export interface EntryDetectionResult {
    /** Whether to use virtual client entry */
    useVirtualClient: boolean;
    /** Whether to use virtual server entry */
    useVirtualServer: boolean;
    /** Whether to use virtual HTML template */
    useVirtualHtml: boolean;
    /** Path to custom client entry if found */
    customClientPath?: string;
    /** Path to custom server entry if found */
    customServerPath?: string;
    /** Path to custom HTML template if found */
    customHtmlPath?: string;
    /** Path to global CSS if found */
    globalCssPath?: string;
}

/**
 * Detect if user has custom entry points
 */
export function detectCustomEntries(root: string, config: SSGConfig): EntryDetectionResult {
    // Custom client entry paths (if found, user has custom setup)
    const clientPaths = [
        'src/main.tsx',
        'src/main.ts',
        'src/entry-client.tsx',
        'src/entry-client.ts',
        'src/entry.tsx',
        'src/entry.ts',
    ];

    const serverPaths = [
        'src/entry-server.tsx',
        'src/entry-server.ts',
    ];

    const htmlPaths = [
        'index.html',
    ];

    // Global CSS to auto-import (checked in order of preference)
    const cssPaths = [
        'src/styles/global.css',
        'src/styles/main.css',
        'src/styles/index.css',
        'src/style.css',
        'src/global.css',
        'src/index.css',
    ];

    let customClientPath: string | undefined;
    let customServerPath: string | undefined;
    let customHtmlPath: string | undefined;
    let globalCssPath: string | undefined;

    // Check for custom client entry
    for (const p of clientPaths) {
        const fullPath = path.join(root, p);
        if (fs.existsSync(fullPath)) {
            customClientPath = fullPath;
            break;
        }
    }

    // Check for custom server entry
    for (const p of serverPaths) {
        const fullPath = path.join(root, p);
        if (fs.existsSync(fullPath)) {
            customServerPath = fullPath;
            break;
        }
    }

    // Check for custom HTML template
    for (const p of htmlPaths) {
        const fullPath = path.join(root, p);
        if (fs.existsSync(fullPath)) {
            customHtmlPath = fullPath;
            break;
        }
    }

    // Check for global CSS
    for (const p of cssPaths) {
        const fullPath = path.join(root, p);
        if (fs.existsSync(fullPath)) {
            globalCssPath = '/' + p.replace(/\\/g, '/');
            break;
        }
    }

    return {
        useVirtualClient: !customClientPath,
        useVirtualServer: !customServerPath,
        useVirtualHtml: !customHtmlPath,
        customClientPath,
        customServerPath,
        customHtmlPath,
        globalCssPath,
    };
}

/**
 * Generate virtual client entry code
 */
export function generateClientEntry(config: SSGConfig, detection: EntryDetectionResult): string {
    const cssImport = detection.globalCssPath
        ? `import '${detection.globalCssPath}';\n`
        : '';

    // Additional client imports from config
    const additionalImports = (config.clientImports ?? [])
        .map(imp => `import '${imp}';`)
        .join('\n');
    const additionalImportsBlock = additionalImports ? `\n${additionalImports}\n` : '';

    const prefetchDelay = typeof config.prefetch === 'object'
        ? config.prefetch.delay ?? 100
        : 100;

    const prefetchEnabled = config.prefetch !== false;

    return `/**
 * Auto-generated client entry point
 * This file is generated by @sigx/ssg when no custom entry is detected.
 * To customize, create src/main.tsx or src/entry-client.tsx
 */
${cssImport}${additionalImportsBlock}
import { defineApp, component } from 'sigx';
import { createRouter, createWebHistory } from '@sigx/router';
import { ssrClientPlugin } from '@sigx/ssg/client';
import routes from 'virtual:ssg-routes';
import { setupLayouts, LayoutRouter } from 'virtual:generated-layouts';
${prefetchEnabled ? `import { setupPrefetch } from '@sigx/ssg/client';` : ''}

// Apply layouts to routes (annotates routes with layout info)
const layoutRoutes = setupLayouts(routes);

// Create router with browser history
const router = createRouter({
    history: createWebHistory('${config.base || '/'}'),
    routes: layoutRoutes,
    scrollBehavior(to, from, savedPosition) {
        if (savedPosition) return savedPosition;
        if (to.hash) return { el: to.hash };
        return { top: 0 };
    },
});

// Root app component - uses LayoutRouter which preserves layouts across navigation
const App = component(() => {
    return () => <LayoutRouter />;
});

// Hydrate the server-rendered HTML
defineApp(<App />)
    .use(router)
    .use(ssrClientPlugin)
    .hydrate('#app');

${prefetchEnabled ? `// Enable link prefetching for faster navigation
setupPrefetch({ delay: ${prefetchDelay} });` : ''}
`;
}

/**
 * Generate virtual server entry code
 */
export function generateServerEntry(config: SSGConfig): string {
    return `/**
 * Auto-generated server entry point
 * This file is generated by @sigx/ssg when no custom entry is detected.
 * To customize, create src/entry-server.tsx
 */
import { renderToString } from '@sigx/server-renderer/server';
import { defineApp } from 'sigx';
import { createRouter, createMemoryHistory } from '@sigx/router';
import routes from 'virtual:ssg-routes';
import { setupLayouts, LayoutRouter } from 'virtual:generated-layouts';

// Pre-process routes with layouts once at module load time (not per-render)
const routesWithLayouts = setupLayouts(routes);

/**
 * Render the app to HTML string for a given URL
 */
export async function render(url, context) {
    // Create router with memory history for SSR
    // Note: We must create a new router per render because history is URL-specific
    const router = createRouter({
        routes: routesWithLayouts,
        history: createMemoryHistory({
            base: '${config.base || '/'}',
            initialLocation: url || '/',
        }),
    });

    // Create app with router - router's install() sets up DI via app.defineProvide()
    const app = defineApp(<LayoutRouter />).use(router);

    const html = await renderToString(app);
    return html;
}
`;
}

/**
 * Generate virtual HTML template
 */
export function generateHtmlTemplate(config: SSGConfig): string {
    const site = config.site || {};
    const lang = site.lang || 'en';
    const title = site.title || 'SignalX App';
    const description = site.description || '';
    const favicon = site.favicon || '/favicon.ico';
    const themeColor = site.themeColor || '#000000';
    const ogImage = site.ogImage || '';
    const url = site.url || '';
    const twitter = site.twitter || '';
    const fonts = site.fonts || [];

    // Build font preconnect and stylesheet links
    let fontLinks = '';
    if (fonts.length > 0) {
        fontLinks = `
    <link rel="preconnect" href="https://fonts.googleapis.com" />
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
    <link href="https://fonts.googleapis.com/css2?family=${fonts.join('&family=')}&display=swap" rel="stylesheet" />`;
    }

    // Build OG meta tags
    let ogTags = '';
    if (url || ogImage) {
        ogTags = `
    <!-- Open Graph -->
    <meta property="og:type" content="website" />
    <meta property="og:title" content="${title}" />
    <meta property="og:description" content="${description}" />${url ? `
    <meta property="og:url" content="${url}" />` : ''}${ogImage ? `
    <meta property="og:image" content="${ogImage}" />` : ''}`;
    }

    // Build Twitter card tags
    let twitterTags = '';
    if (twitter || ogImage) {
        twitterTags = `
    <!-- Twitter Card -->
    <meta name="twitter:card" content="${ogImage ? 'summary_large_image' : 'summary'}" />${twitter ? `
    <meta name="twitter:site" content="@${twitter}" />` : ''}
    <meta name="twitter:title" content="${title}" />
    <meta name="twitter:description" content="${description}" />${ogImage ? `
    <meta name="twitter:image" content="${ogImage}" />` : ''}`;
    }

    return `<!DOCTYPE html>
<html lang="${lang}">
<head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta name="description" content="${description}" />
    <meta name="theme-color" content="${themeColor}" />
    <link rel="icon" type="image/x-icon" href="${favicon}" />${fontLinks}${ogTags}${twitterTags}
    <title>${title}</title>
    <!--head-tags-->
</head>
<body>
    <div id="app"><!--app-html--></div>
    <script type="module" src="/@ssg/client.tsx"></script>
</body>
</html>
`;
}

/**
 * Generate HTML template for production build
 * Uses the actual client entry path instead of virtual module
 */
export function generateProductionHtmlTemplate(config: SSGConfig, clientEntryPath: string): string {
    const site = config.site || {};
    const lang = site.lang || 'en';
    const title = site.title || 'SignalX App';
    const description = site.description || '';
    const favicon = site.favicon || '/favicon.ico';
    const themeColor = site.themeColor || '#000000';
    const ogImage = site.ogImage || '';
    const url = site.url || '';
    const twitter = site.twitter || '';
    const fonts = site.fonts || [];

    // Build font preconnect and stylesheet links
    let fontLinks = '';
    if (fonts.length > 0) {
        fontLinks = `
    <link rel="preconnect" href="https://fonts.googleapis.com" />
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
    <link href="https://fonts.googleapis.com/css2?family=${fonts.join('&family=')}&display=swap" rel="stylesheet" />`;
    }

    // Build OG meta tags
    let ogTags = '';
    if (url || ogImage) {
        ogTags = `
    <!-- Open Graph -->
    <meta property="og:type" content="website" />
    <meta property="og:title" content="${title}" />
    <meta property="og:description" content="${description}" />${url ? `
    <meta property="og:url" content="${url}" />` : ''}${ogImage ? `
    <meta property="og:image" content="${ogImage}" />` : ''}`;
    }

    // Build Twitter card tags
    let twitterTags = '';
    if (twitter || ogImage) {
        twitterTags = `
    <!-- Twitter Card -->
    <meta name="twitter:card" content="${ogImage ? 'summary_large_image' : 'summary'}" />${twitter ? `
    <meta name="twitter:site" content="@${twitter}" />` : ''}
    <meta name="twitter:title" content="${title}" />
    <meta name="twitter:description" content="${description}" />${ogImage ? `
    <meta name="twitter:image" content="${ogImage}" />` : ''}`;
    }

    return `<!DOCTYPE html>
<html lang="${lang}">
<head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta name="description" content="${description}" />
    <meta name="theme-color" content="${themeColor}" />
    <link rel="icon" type="image/x-icon" href="${favicon}" />${fontLinks}${ogTags}${twitterTags}
    <title>${title}</title>
    <!--head-tags-->
</head>
<body>
    <div id="app"><!--app-html--></div>
    <script type="module" src="${clientEntryPath}"></script>
</body>
</html>
`;
}
